global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi_app"
    static_configs:
      - targets: ["app:8000"]
        labels:
          application: "CodeVenture"
          env: "production"
